CREATE DATABASE CAPTATEC
GO

USE CAPTATEC
GO

CREATE TABLE CLIENTE(
CLIENTEID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(15) NOT NULL UNIQUE,
TIPO_CLI INT NOT NULL,
SEXO VARCHAR(1) NULL,
SIT_CLI INT NOT NULL,
);

CREATE TABLE TIPO_CLIENTE(
TIPOCLIID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
TIPOCLIENTE VARCHAR(50) NOT NULL,
);

CREATE TABLE SITUACAO_CLIENTE(
SITUACAOCLIID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
SITUACAOCLIENTE VARCHAR(50) NOT NULL,
);

ALTER TABLE CLIENTE ADD CONSTRAINT FK_TIPO_CLI FOREIGN KEY (TIPO_CLI) REFERENCES TIPO_CLIENTE(TIPOCLIID);
ALTER TABLE CLIENTE ADD CONSTRAINT FK_SIT_CLI FOREIGN KEY (SIT_CLI) REFERENCES SITUACAO_CLIENTE(SITUACAOCLIID);

---------------------------------------------------------------------------------------------  *** CREATE PROCEDURES - CLIENTES ***

USE CAPTATEC
GO

CREATE PROCEDURE SelectAllClient AS
SELECT * FROM CLIENTE
GO

USE CAPTATEC
GO

CREATE PROCEDURE SelectAClient @CPF VARCHAR(15) AS
SELECT * FROM CLIENTE WHERE CPF = @CPF
GO

USE CAPTATEC
GO

CREATE PROCEDURE InsertClient @NOME VARCHAR(100), @CPF VARCHAR(15), @TIPO_CLI INT, @SEXO VARCHAR(1), @SIT_CLI INT AS
BEGIN
DECLARE @ROW TABLE(CLIENTEID INT, NOME VARCHAR(100), CPF VARCHAR(15), TIPO_CLI INT, SEXO VARCHAR(2), SIT_CLI INT)
INSERT INTO @ROW (CLIENTEID, NOME, CPF, TIPO_CLI, SEXO, SIT_CLI) SELECT * FROM CLIENTE WHERE CPF = @CPF;
IF (SELECT CLIENTEID FROM @ROW) IS NULL
BEGIN
INSERT INTO CLIENTE VALUES(@NOME, @CPF, @TIPO_CLI, @SEXO, @SIT_CLI);
SELECT * FROM CLIENTE WHERE CPF = @CPF;
END
ELSE
BEGIN
SELECT * FROM @ROW;
END
END
GO

USE CAPTATEC
GO

CREATE PROCEDURE EditClient @CLIENTEID INT, @NOME VARCHAR(100), @CPF VARCHAR(15), @TIPO_CLI INT, @SEXO VARCHAR(1), @SIT_CLI INT AS
UPDATE CLIENTE SET NOME = @NOME, CPF = @CPF, TIPO_CLI = @TIPO_CLI, SEXO = @SEXO, SIT_CLI = @SIT_CLI
WHERE CLIENTEID = @CLIENTEID;
SELECT * FROM CLIENTE WHERE CLIENTEID = @CLIENTEID;
GO

USE CAPTATEC
GO

CREATE PROCEDURE DeleteClient @CPF VARCHAR(15) AS
BEGIN
DECLARE @ROW TABLE(CLIENTEID INT, NOME VARCHAR(100), CPF VARCHAR(15), TIPO_CLI INT, SEXO VARCHAR(2), SIT_CLI INT)
INSERT INTO @ROW (CLIENTEID, NOME, CPF, TIPO_CLI, SEXO, SIT_CLI) SELECT * FROM CLIENTE WHERE CPF = @CPF;
IF (SELECT CLIENTEID FROM @ROW) <> ''
BEGIN
DELETE FROM CLIENTE WHERE CPF = @CPF;
SELECT * FROM @ROW;
END
ELSE
BEGIN
SELECT * FROM @ROW;
END
END
GO

---------------------------------------------------------------------------------------------  *** BASE ***

USE CAPTATEC
GO

INSERT INTO TIPO_CLIENTE VALUES('Calçado');
INSERT INTO TIPO_CLIENTE VALUES('Vestuário');
INSERT INTO TIPO_CLIENTE VALUES('Metalúrgica');

INSERT INTO SITUACAO_CLIENTE VALUES('Ativo');
INSERT INTO SITUACAO_CLIENTE VALUES('Inativo');
INSERT INTO SITUACAO_CLIENTE VALUES('Negócio');

USE CAPTATEC
GO

EXEC dbo.InsertClient @NOME ='JOSE FERREIRA DA SILVA', @CPF = '25673278589', @TIPO_CLI = 1, @SEXO = 'M', @SIT_CLI = 3;
EXEC dbo.InsertClient @NOME ='MARCIA COELHO', @CPF = '73256421552', @TIPO_CLI = 2, @SEXO = 'F', @SIT_CLI = 2;
EXEC dbo.InsertClient @NOME ='JURACIR DOS ANJOS MELLO', @CPF = '25648565415', @TIPO_CLI = 3, @SEXO = '', @SIT_CLI = 1;
EXEC dbo.InsertClient @NOME ='LOHAINE MACHADO RIOT', @CPF = '54845763225', @TIPO_CLI = 1, @SEXO = 'F', @SIT_CLI = 3;
EXEC dbo.InsertClient @NOME ='LOURENÇO DOS SANTOS ASSIS', @CPF = '24863222233', @TIPO_CLI = 2, @SEXO = 'M', @SIT_CLI = 1;